config/routes.rb
Agendor::Application.routes.draw do
  devise_for :users
  root :to => "signatures#index"
  resources :signatures

end

app/models/signature.rb
class Signature < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :signature
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  # GET /signatures
  # GET /signatures.xml
  def index
    @signatures = Signature.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @signatures }
    end
  end

  # GET /signatures/1
  # GET /signatures/1.xml
  def show
    @signature = Signature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @signature }
    end
  end

  # GET /signatures/new
  # GET /signatures/new.xml
  def new
    @signature = Signature.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @signature }
    end
  end

  # GET /signatures/1/edit
  def edit
    @signature = Signature.find(params[:id])
  end

  # POST /signatures
  # POST /signatures.xml
  def create
    @signature = Signature.new(params[:signature])

    respond_to do |format|
      if @signature.save
        format.html { redirect_to(@signature, :notice => 'Signature was successfully created.') }
        format.xml  { render :xml => @signature, :status => :created, :location => @signature }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @signature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /signatures/1
  # PUT /signatures/1.xml
  def update
    @signature = Signature.find(params[:id])

    respond_to do |format|
      if @signature.update_attributes(params[:signature])
        format.html { redirect_to(@signature, :notice => 'Signature was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @signature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /signatures/1
  # DELETE /signatures/1.xml
  def destroy
    @signature = Signature.find(params[:id])
    @signature.destroy

    respond_to do |format|
      format.html { redirect_to(signatures_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controler.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/layouts/application.html.slim
! doctype
html
  head
    title agendor
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  body
    p.notice= notice
    p.alert= alert
    #header
      - if user_signed_in?
        li = current_user.email
        li = link_to("Logout", destroy_user_session_path)
      - else
        li = link_to("Login", new_user_session_path)
    #content
      = yield
    #footer
      | agendor is libre software

app/views/signatures/_form.html.slim
= form_for @signature do |f|
  -if @signature.errors.any?
    #error_explanation
      h2 = "#{pluralize(@signature.errors.count, "error")} prohibited this signature from being saved:"
      ul
        - @signature.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/signatures/edit.html.slim
h1 Editing signature

== render 'form'

= link_to 'Show', @signature
`|
= link_to 'Back', signatures_path

app/views/signatures/index.html.slim
h1 Listing signatures

table
  tr
    th User
    th Name
    th Content
    th
    th
    th

  - @signatures.each do |signature|
    tr
      td= signature.user_id
      td= signature.name
      td= signature.content
      td= link_to 'Show', signature
      td= link_to 'Edit', edit_signature_path(signature)
      td= link_to 'Destroy', signature, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Signature', new_signature_path

app/views/signatures/new.html.slim
h1 New signature

== render 'form'

= link_to 'Back', signatures_path

app/views/signatures/show.html.slim
p#notice = notice

p
  b User:
  = @signature.user_id
p
  b Name:
  = @signature.name
p
  b Content:
  = @signature.content

= link_to 'Edit', edit_signature_path(@signature)
`|
= link_to 'Back', signatures_path